"""Rust code generation against the HSSN contract ABI (hssn-contract).

Takes a checked Program and emits a complete cargo project (Cargo.toml,
src/lib.rs) that compiles to wasm32-unknown-unknown and runs in the HSSN
VM. Safety properties the generator guarantees regardless of source:

- all int arithmetic is checked (overflow aborts the action, reverting it)
- every state map lives in its own key prefix under the contract namespace
- require() failures abort via env.abort, so all effects revert atomically
- config is written once by the generated `init` action, read-only after

Value encoding (deterministic, little-endian): int = u64 LE (8 bytes),
bool = 1 byte, address = 32 raw bytes, str = u32 LE length + UTF-8 bytes.
Action arguments use the same encoding in declaration order (the SDK's
ArgReader/args helpers match it).
"""

from hssndsl.ast_nodes import (
    Assign, Attr, BinOp, BoolLit, BoolOp, Compare, Ctor, EmitStmt, Exists,
    If, IntLit, Name, NotOp, Program, Require, StrLit, TransferStmt,
)

RUST_TYPES = {"int": "u64", "str": "String", "bool": "bool", "address": "[u8; 32]"}


def snake(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def default_literal(field) -> str:
    if field.ty == "int":
        return f"{field.default}u64"
    if field.ty == "str":
        return f"{rust_string(field.default)}.to_string()"
    if field.ty == "bool":
        return "true" if field.default else "false"
    raise AssertionError(f"no default literal for {field.ty}")


class _Writer:
    def __init__(self):
        self.lines: list[str] = []
        self.indent = 0

    def w(self, line: str = ""):
        self.lines.append("    " * self.indent + line if line else "")

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


def _uses(node, want_kind: str) -> bool:
    """Does any expression under `node` reference the given builtin/name?"""
    if isinstance(node, Name):
        if want_kind == "config":
            return False
        return node.kind == want_kind
    if isinstance(node, Attr):
        if want_kind == "config" and isinstance(node.obj, Name) and node.obj.id == "config":
            return True
        return _uses(node.obj, want_kind)
    if isinstance(node, (BinOp, Compare)):
        return _uses(node.left, want_kind) or _uses(node.right, want_kind)
    if isinstance(node, BoolOp):
        return any(_uses(p, want_kind) for p in node.parts)
    if isinstance(node, NotOp):
        return _uses(node.operand, want_kind)
    if isinstance(node, (Exists,)):
        return _uses(node.key, want_kind)
    if isinstance(node, Ctor):
        return any(_uses(e, want_kind) for _, e in node.kwargs)
    if isinstance(node, Require):
        return _uses(node.cond, want_kind)
    if isinstance(node, Assign):
        return _uses(node.target, want_kind) or _uses(node.value, want_kind)
    if isinstance(node, If):
        return (
            any(_uses(c, want_kind) or any(_uses(s, want_kind) for s in b)
                for c, b in node.branches)
            or any(_uses(s, want_kind) for s in node.orelse)
        )
    if hasattr(node, "key"):
        return _uses(node.key, want_kind)
    return False


class _CodeGen:
    def __init__(self, program: Program):
        self.p = program
        self.states = {s.name: s for s in program.states}
        self.out = _Writer()
        self.tmp = 0

    def fresh(self, base: str) -> str:
        self.tmp += 1
        return f"__{base}{self.tmp}"

    # ------------------------------------------------------------ program

    def generate(self) -> str:
        w = self.out
        w.w(f"//! Generated by hssndsl from contract {self.p.name} — do not edit.")
        w.w("#![allow(unused_variables, unused_mut, clippy::all)]")
        w.w()
        w.w("use hssn_contract as c;")
        w.w()
        self.emit_codec_helpers()
        if self.p.config:
            self.emit_config()
        for state in self.p.states:
            self.emit_state(state)
        for action in self.p.actions:
            self.emit_action(action)
        return w.text()

    def emit_codec_helpers(self):
        w = self.out
        w.w("struct Dec<'a> { d: &'a [u8], o: usize }")
        w.w("impl<'a> Dec<'a> {")
        w.indent += 1
        w.w("fn new(d: &'a [u8]) -> Self { Self { d, o: 0 } }")
        w.w("fn take(&mut self, n: usize) -> &'a [u8] {")
        w.w("    if self.o + n > self.d.len() { c::fail(\"corrupt state value\"); }")
        w.w("    let s = &self.d[self.o..self.o + n]; self.o += n; s")
        w.w("}")
        w.w("fn u64(&mut self) -> u64 { u64::from_le_bytes(self.take(8).try_into().unwrap()) }")
        w.w("fn boolean(&mut self) -> bool { self.take(1)[0] == 1 }")
        w.w("fn addr(&mut self) -> [u8; 32] { self.take(32).try_into().unwrap() }")
        w.w("fn string(&mut self) -> String {")
        w.w("    let n = u32::from_le_bytes(self.take(4).try_into().unwrap()) as usize;")
        w.w("    String::from_utf8(self.take(n).to_vec())")
        w.w("        .unwrap_or_else(|_| c::fail(\"corrupt state string\"))")
        w.w("}")
        w.indent -= 1
        w.w("}")
        w.w()
        w.w("fn enc_u64(out: &mut Vec<u8>, v: u64) { out.extend_from_slice(&v.to_le_bytes()); }")
        w.w("fn enc_bool(out: &mut Vec<u8>, v: bool) { out.push(if v { 1 } else { 0 }); }")
        w.w("fn enc_addr(out: &mut Vec<u8>, v: &[u8; 32]) { out.extend_from_slice(v); }")
        w.w("fn enc_str(out: &mut Vec<u8>, v: &str) {")
        w.w("    out.extend_from_slice(&(v.len() as u32).to_le_bytes());")
        w.w("    out.extend_from_slice(v.as_bytes());")
        w.w("}")
        w.w()
        w.w("fn add(a: u64, b: u64) -> u64 {")
        w.w("    a.checked_add(b).unwrap_or_else(|| c::fail(\"integer overflow\"))")
        w.w("}")
        w.w("fn sub(a: u64, b: u64) -> u64 {")
        w.w("    a.checked_sub(b).unwrap_or_else(|| c::fail(\"integer underflow\"))")
        w.w("}")
        w.w()
        w.w("fn arg_bool(args: &mut c::ArgReader) -> bool { args.u64() != 0 }")
        w.w("fn arg_str(args: &mut c::ArgReader) -> String {")
        w.w("    String::from_utf8(args.bytes()).unwrap_or_else(|_| c::fail(\"args: bad utf-8\"))")
        w.w("}")
        w.w()

    # ------------------------------------------------------------- config

    def emit_config(self):
        w = self.out
        w.w("struct Config {")
        for f in self.p.config:
            w.w(f"    {f.name}: {RUST_TYPES[f.ty]},")
        w.w("}")
        w.w()
        w.w("fn load_config() -> Config {")
        w.w("    let raw = c::storage_get(b\"cfg\")")
        w.w("        .unwrap_or_else(|| c::fail(\"contract not initialized (call init)\"));")
        w.w("    let mut d = Dec::new(&raw);")
        w.w("    Config {")
        for f in self.p.config:
            w.w(f"        {f.name}: d.{self.dec_call(f.ty)},")
        w.w("    }")
        w.w("}")
        w.w()
        # the generated one-shot initializer
        w.w("#[unsafe(no_mangle)]")
        w.w("pub extern \"C\" fn init() -> i32 {")
        w.indent += 1
        w.w("if c::storage_get(b\"cfg\").is_some() { c::fail(\"already initialized\"); }")
        w.w("let mut args = c::ArgReader::new();")
        w.w("let mut out: Vec<u8> = Vec::new();")
        for f in self.p.config:
            w.w(f"let {f.name}: {RUST_TYPES[f.ty]} = {self.arg_call(f.ty)};")
        for f in self.p.config:
            w.w(self.enc_stmt("out", f.ty, f.name))
        w.w("c::storage_set(b\"cfg\", &out);")
        w.w("0")
        w.indent -= 1
        w.w("}")
        w.w()

    def dec_call(self, ty: str) -> str:
        return {"int": "u64()", "str": "string()", "bool": "boolean()", "address": "addr()"}[ty]

    def arg_call(self, ty: str) -> str:
        return {
            "int": "args.u64()",
            "str": "arg_str(&mut args)",
            "bool": "arg_bool(&mut args)",
            "address": "args.address()",
        }[ty]

    def enc_stmt(self, out: str, ty: str, expr: str) -> str:
        if ty == "int":
            return f"enc_u64(&mut {out}, {expr});"
        if ty == "bool":
            return f"enc_bool(&mut {out}, {expr});"
        if ty == "address":
            return f"enc_addr(&mut {out}, &{expr});"
        return f"enc_str(&mut {out}, &{expr});"

    # -------------------------------------------------------------- state

    def emit_state(self, state):
        w = self.out
        s = snake(state.name)
        w.w(f"struct {state.name} {{")
        for f in state.fields:
            w.w(f"    {f.name}: {RUST_TYPES[f.ty]},")
        w.w("}")
        w.w()
        key_ty = RUST_TYPES[state.key_ty]
        key_ref = "u64" if state.key_ty == "int" else "&[u8; 32]"
        w.w(f"fn key_{s}(k: {key_ref}) -> Vec<u8> {{")
        w.w(f"    let mut v = b\"s:{state.name}:\".to_vec();")
        if state.key_ty == "int":
            w.w("    v.extend_from_slice(&k.to_le_bytes());")
        else:
            w.w("    v.extend_from_slice(k);")
        w.w("    v")
        w.w("}")
        w.w(f"fn decode_{s}(raw: &[u8]) -> {state.name} {{")
        w.w("    let mut d = Dec::new(raw);")
        w.w(f"    {state.name} {{")
        for f in state.fields:
            w.w(f"        {f.name}: d.{self.dec_call(f.ty)},")
        w.w("    }")
        w.w("}")
        w.w(f"fn save_{s}(key: &[u8], v: &{state.name}) {{")
        w.w("    let mut out: Vec<u8> = Vec::new();")
        for f in state.fields:
            w.w("    " + self.enc_stmt("out", f.ty, f"v.{f.name}"))
        w.w("    c::storage_set(key, &out);")
        w.w("}")
        if state.defaultable:
            w.w(f"fn load_{s}(key: &[u8]) -> {state.name} {{")
            w.w(f"    match c::storage_get(key) {{")
            w.w(f"        Some(raw) => decode_{s}(&raw),")
            w.w(f"        None => {state.name} {{")
            for f in state.fields:
                w.w(f"            {f.name}: {default_literal(f)},")
            w.w("        },")
            w.w("    }")
            w.w("}")
        else:
            w.w(f"fn load_{s}(key: &[u8]) -> {state.name} {{")
            w.w("    let raw = c::storage_get(key)")
            w.w(f"        .unwrap_or_else(|| c::fail(\"no such {state.name} entry\"));")
            w.w(f"    decode_{s}(&raw)")
            w.w("}")
        w.w()

    # ------------------------------------------------------------- actions

    def emit_action(self, action):
        w = self.out
        w.w("#[unsafe(no_mangle)]")
        w.w(f"pub extern \"C\" fn {action.name}() -> i32 {{")
        w.indent += 1
        if action.params:
            w.w("let mut args = c::ArgReader::new();")
            for p in action.params:
                w.w(f"let {p.name}: {RUST_TYPES[p.ty]} = {self.arg_call(p.ty)};")
        needs_sender = any(_uses(s, "sender") for s in action.body)
        needs_config = any(_uses(s, "config") for s in action.body)
        if needs_sender:
            w.w("let sender: [u8; 32] = c::caller();")
        if needs_config:
            w.w("let config = load_config();")
        self.emit_body(action.body, action)
        w.w("0")
        w.indent -= 1
        w.w("}")
        w.w()

    def emit_body(self, body, action):
        for stmt in body:
            self.emit_stmt(stmt, action)

    def emit_stmt(self, stmt, action):
        w = self.out
        if isinstance(stmt, Require):
            w.w(f"if !({self.expr(stmt.cond)}) {{ c::fail({rust_string(stmt.msg)}); }}")
        elif isinstance(stmt, If):
            for i, (cond, branch) in enumerate(stmt.branches):
                kw = "if" if i == 0 else "} else if"
                w.w(f"{kw} {self.expr(cond)} {{")
                w.indent += 1
                self.emit_body(branch, action)
                w.indent -= 1
            if stmt.orelse:
                w.w("} else {")
                w.indent += 1
                self.emit_body(stmt.orelse, action)
                w.indent -= 1
            w.w("}")
        elif isinstance(stmt, TransferStmt):
            w.w(f"if !c::transfer(&({self.expr(stmt.to)}), {self.expr(stmt.amount)}) {{")
            w.w('    c::fail("transfer failed: insufficient contract balance");')
            w.w("}")
        elif isinstance(stmt, EmitStmt):
            w.w(f"c::emit(({self.expr(stmt.value)}).as_bytes());")
        elif isinstance(stmt, Assign):
            self.emit_assign(stmt, action)
        else:
            raise AssertionError(f"unsupported statement {stmt!r}")

    def key_expr(self, index) -> str:
        state = self.states[index.map_name]
        s = snake(state.name)
        key = self.expr(index.key)
        if state.key_ty == "address":
            return f"key_{s}(&{key})"
        return f"key_{s}({key})"

    def emit_assign(self, stmt, action):
        from hssndsl.ast_nodes import Index  # local import to match parser module
        w = self.out
        target, value = stmt.target, stmt.value

        # Map[key] = Ctor(...): build the struct and save immediately.
        if isinstance(target, Index):
            state = self.states[target.map_name]
            s = snake(state.name)
            provided = dict(value.kwargs)
            w.w(f"let __new = {state.name} {{")
            for f in state.fields:
                if f.name in provided:
                    w.w(f"    {f.name}: {self.expr(provided[f.name])},")
                else:
                    w.w(f"    {f.name}: {default_literal(f)},")
            w.w("};")
            w.w(f"save_{s}(&{self.key_expr(target)}, &__new);")
            return

        # local binding or scalar assignment
        if isinstance(target, Name):
            if getattr(target, "kind", None) == "bound":
                state = self.states[target.binding_state]
                s = snake(state.name)
                key_var = f"__key_{target.id}"
                w.w(f"let {key_var} = {self.key_expr(value)};")
                w.w(f"let mut {target.id} = load_{s}(&{key_var});")
                return
            mutability = "let mut" if target.id in action.reassigned_locals else "let"
            if stmt.op == "+=":
                w.w(f"{target.id} = add({target.id}, {self.expr(value)});")
            elif stmt.op == "-=":
                w.w(f"{target.id} = sub({target.id}, {self.expr(value)});")
            elif target.id in action.reassigned_locals and self.is_second_assign(target, action):
                w.w(f"{target.id} = {self.expr(value)};")
            else:
                # first assignment
                if not hasattr(action, "_declared"):
                    action._declared = set()
                if target.id in action._declared:
                    w.w(f"{target.id} = {self.expr(value)};")
                else:
                    action._declared.add(target.id)
                    w.w(f"{mutability} {target.id} = {self.expr(value)};")
            return

        # field write: handle.field = v  or  Map[key].field = v
        if isinstance(target, Attr):
            obj = target.obj
            if isinstance(obj, Name):  # bound handle
                state = self.states[action.bindings[obj.id]]
                s = snake(state.name)
                field = next(f for f in state.fields if f.name == target.attr)
                lhs = f"{obj.id}.{target.attr}"
                self.emit_field_update(lhs, field, stmt)
                w.w(f"save_{s}(&__key_{obj.id}, &{obj.id});")
                return
            # Map[key].field = v
            state = self.states[obj.map_name]
            s = snake(state.name)
            field = next(f for f in state.fields if f.name == target.attr)
            tmp = self.fresh("e")
            keytmp = self.fresh("k")
            w.w(f"let {keytmp} = {self.key_expr(obj)};")
            w.w(f"let mut {tmp} = load_{s}(&{keytmp});")
            self.emit_field_update(f"{tmp}.{target.attr}", field, stmt)
            w.w(f"save_{s}(&{keytmp}, &{tmp});")
            return

        raise AssertionError("invalid assignment target")

    def is_second_assign(self, target, action) -> bool:
        declared = getattr(action, "_declared", set())
        return target.id in declared

    def emit_field_update(self, lhs: str, field, stmt):
        w = self.out
        rhs = self.expr(stmt.value)
        if stmt.op == "+=":
            w.w(f"{lhs} = add({lhs}, {rhs});")
        elif stmt.op == "-=":
            w.w(f"{lhs} = sub({lhs}, {rhs});")
        else:
            w.w(f"{lhs} = {rhs};")

    # ---------------------------------------------------------- expressions

    def expr(self, e) -> str:
        from hssndsl.ast_nodes import Index
        if isinstance(e, IntLit):
            return f"{e.value}u64"
        if isinstance(e, StrLit):
            return f"{rust_string(e.value)}.to_string()"
        if isinstance(e, BoolLit):
            return "true" if e.value else "false"
        if isinstance(e, Name):
            if e.kind == "sender":
                return "sender"
            if e.kind == "height":
                return "c::block_height()"
            if e.kind == "value":
                return "c::attached_value()"
            if e.ty == "str":
                return f"{e.id}.clone()"
            return e.id
        if isinstance(e, Attr):
            obj = e.obj
            if isinstance(obj, Name) and obj.id == "config":
                base = f"config.{e.attr}"
            elif isinstance(obj, Name):
                base = f"{obj.id}.{e.attr}"
            elif isinstance(obj, Index):
                state = self.states[obj.map_name]
                s = snake(state.name)
                base = f"load_{s}(&{self.key_expr(obj)}).{e.attr}"
            else:
                raise AssertionError("bad attr")
            return f"{base}.clone()" if e.ty == "str" else base
        if isinstance(e, Exists):
            fake = type("K", (), {"map_name": e.map_name, "key": e.key})()
            return f"c::storage_get(&{self.key_expr(fake)}).is_some()"
        if isinstance(e, BinOp):
            fn = "add" if e.op == "+" else "sub"
            return f"{fn}({self.expr(e.left)}, {self.expr(e.right)})"
        if isinstance(e, Compare):
            return f"({self.cmp_operand(e.left)} {e.op} {self.cmp_operand(e.right)})"
        if isinstance(e, BoolOp):
            op = "&&" if e.op == "and" else "||"
            return "(" + f" {op} ".join(self.expr(p) for p in e.parts) + ")"
        if isinstance(e, NotOp):
            return f"!({self.expr(e.operand)})"
        raise AssertionError(f"unsupported expression {e!r}")

    def cmp_operand(self, e) -> str:
        # Compare strings by &str to avoid moving; everything else by value.
        s = self.expr(e)
        if e.ty == "str":
            return f"{s}.as_str().to_owned()" if False else f"({s})"
        return s


CARGO_TOML = """[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hssn-contract = {{ path = {runtime_path} }}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
"""


def generate(program: Program, runtime_path: str) -> dict[str, str]:
    """Emit the cargo project as {relative_path: contents}."""
    lib = _CodeGen(program).generate()
    name = snake(program.name)
    cargo = CARGO_TOML.format(name=name, runtime_path=rust_string(runtime_path))
    return {"Cargo.toml": cargo, "src/lib.rs": lib}
